/**
 * Forge 1.20.1 项目骨架文件生成器（Task 4-D）
 *
 * 生成 Forge MDK 项目所需的非 Java 文件：
 *   - build.gradle           (ForgeGradle 6.0.x 配置)
 *   - gradle.properties      (版本与 mod 元信息)
 *   - settings.gradle
 *   - gradlew / gradlew.bat  (Forge MDK 自带 wrapper 脚本)
 *   - gradle/wrapper/gradle-wrapper.properties
 *   - gradle/wrapper/gradle-wrapper.jar (二进制占位 — 实际下载需用户首次运行 ./gradlew)
 *   - src/main/resources/META-INF/mods.toml
 *   - src/main/resources/pack.mcmeta
 *   - README.md
 *   - .gitignore
 *
 * 设计要点：
 *  - gradle.properties 中所有 ${var} 占位由 build.gradle / mods.toml 在
 *    processResources 阶段替换。
 *  - mods.toml 的 loaderVersion 必须 ≥ [47,) 才能匹配 Forge 47.3.x。
 *  - Java 17 是 1.20.1 的最低要求。
 *  - gradlew 脚本为 Forge MDK 标准 wrapper，用户首次运行 ./gradlew 时
 *    会自动下载 gradle-wrapper.jar（这里 jar 不内置，避免 ZIP 过大）。
 */

import type { CodegenProject, GeneratedFile } from './types'
import { buildJavaPackage } from './naming'

/* ------------------------------------------------------------------ */
/* gradle.properties                                                   */
/* ------------------------------------------------------------------ */

function genGradleProperties(project: CodegenProject): string {
  const mc = project.mcVersion || '1.20.1'
  const forge = project.forgeVersion || '47.3.7'
  const groupId = buildJavaPackage(project.modId, project.author)
  return `# Gradle / JVM 配置
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.debug=false

# Minecraft / Forge 版本（ForgeGradle 6.0.x）
minecraft_version=${mc}
minecraft_version_range=[1.20.1,1.21)
forge_version=${forge}
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=${mc}

# 模组元信息
mod_id=${project.modId}
mod_name=${project.name}
mod_license=MIT
mod_version=${project.version}
mod_group_id=${groupId}
mod_authors=${project.author}
mod_description=${(project.description || 'Generated by NexCube IDE').replace(/\n/g, ' ')}
`
}

/* ------------------------------------------------------------------ */
/* build.gradle                                                        */
/* ------------------------------------------------------------------ */

function genBuildGradle(): string {
  return `// NexCube 自动生成的 build.gradle —— Forge 1.20.1 + ForgeGradle 6.0.x
// 文档：https://docs.minecraftforge.net/

plugins {
    id 'eclipse'
    id 'idea'
    id 'net.minecraftforge.gradle' version '[6.0.16,6.2)'
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

// Forge 1.20.1 最低要求 Java 17
java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: mapping_channel, version: mapping_version

    copyIdeResources = true

    runs {
        configureEach {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods {
                "\${mod_id}" {
                    source sourceSets.main
                }
            }
        }
        client {
            property 'forge.enabledGameTestNamespaces', mod_id
        }
        server {
            property 'forge.enabledGameTestNamespaces', mod_id
            args '--nogui'
        }
        data {
            workingDirectory project.file('run-data')
            args '--mod', mod_id, '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    maven { url = 'https://maven.minecraftforge.net/' }
}

dependencies {
    minecraft "net.minecraftforge:forge:\${minecraft_version}-\${forge_version}"
}

tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            forge_version          : forge_version,
            forge_version_range    : forge_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description,
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replaceProperties + [project: project]
    }
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes([
                'Specification-Title'     : mod_id,
                'Specification-Vendor'    : mod_authors,
                'Specification-Version'   : '1',
                'Implementation-Title'    : project.name,
                'Implementation-Version'  : project.jar.archiveVersion,
                'Implementation-Vendor'   : mod_authors,
                'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

tasks.named('build').configure {
    dependsOn 'jar'
}
`
}

/* ------------------------------------------------------------------ */
/* settings.gradle                                                     */
/* ------------------------------------------------------------------ */

function genSettingsGradle(project: CodegenProject): string {
  return `// NexCube 自动生成的 settings.gradle
pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url = 'https://maven.minecraftforge.net/' }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
}

rootProject.name = '${project.modId}'
`
}

/* ------------------------------------------------------------------ */
/* gradle wrapper                                                      */
/* ------------------------------------------------------------------ */

/**
 * Forge MDK 标准 gradlew 脚本（Unix）。
 * 来源：Forge 1.20.1 MDK 自带版本，仅保留必要部分。
 */
function genGradlewUnix(): string {
  return `#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
##############################################################################

# Resolve links: \$0 may be a link
app_path=\$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=\${app_path%\${app_path##*/}}  # leaves a trailing /; empty if no leading path
    [ -h "\$app_path" ]
do
    ls=\$( ls -ld "\$app_path" )
    link=\${ls#*' -> '}
    case \$link in             #(
      /*)   app_path=\$link ;; #(
      *)    app_path=\$APP_HOME\$link ;;
    esac
done

APP_HOME=\$( cd -P "\${APP_HOME:-./}" > /dev/null && pwd -P ) || exit

APP_NAME="Gradle"
APP_BASE_NAME=\${0##*/}

DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

MAX_FD=maximum

warn () {
    echo "\$*"
} >&2

die () {
    echo
    echo "\$*"
    echo
    exit 1
} >&2

# Determine the Java command to use to start the JVM.
if [ -n "\$JAVA_HOME" ] ; then
    if [ -x "\$JAVA_HOME/jre/sh/java" ] ; then
        JAVACMD=\$JAVA_HOME/jre/sh/java
    else
        JAVACMD=\$JAVA_HOME/bin/java
    fi
    if [ ! -x "\$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: \$JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! cygwin && ! darwin && ! nonstop ; then
    case \$MAX_FD in #(
      max*)
        # In POSIX sh, ulimit -H is undefined. That's why the result is checked to see if it worked.
        MAX_FD=\$( ulimit -H -n ) ||
            warn "Could not query maximum file descriptor limit"
    esac
    case \$MAX_FD in  #(
      '' | soft) :;; #(
      *)
        ulimit -n "\$MAX_FD" ||
            warn "Could not set maximum file descriptor limit to \$MAX_FD"
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D... appname vars
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

CLASSPATH=\$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the JVM.
if [ -n "\$JAVA_HOME" ] ; then
    JAVACMD="\$JAVA_HOME/bin/java"
else
    JAVACMD="java"
fi

exec "\$JAVACMD" \\
    \$DEFAULT_JVM_OPTS \\
    \$JAVA_OPTS \\
    \$GRADLE_OPTS \\
    "-Dorg.gradle.appname=\$APP_BASE_NAME" \\
    -classpath "\$CLASSPATH" \\
    org.gradle.wrapper.GradleWrapperMain \\
    "\$@"
`
}

/** Forge MDK 标准 gradlew.bat（Windows） */
function genGradlewWindows(): string {
  return `@rem
@rem Copyright 2015 the original author or authors.
@rem
@rem Licensed under the Apache License, Version 2.0 (the "License");
@rem you may not use this file except in compliance with the License.
@rem You may obtain a copy of the License at
@rem
@rem      https://www.apache.org/licenses/LICENSE-2.0
@rem

@if "%DEBUG%"=="" @echo off
@rem ##########################################################################
@rem
@rem  Gradle startup script for Windows
@rem
@rem ##########################################################################

@rem Set local scope for the variables with windows NT shell
if "%OS%"=="Windows_NT" setlocal

set DIRNAME=%~dp0
if "%DIRNAME%"=="" set DIRNAME=.
@rem This is normally unused
set APP_BASE_NAME=%~n0
set APP_HOME=%DIRNAME%

@rem Resolve any "." and ".." in APP_HOME to make it shorter.
for %%i in ("%APP_HOME%") do set APP_HOME=%%~fi

@rem Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
set DEFAULT_JVM_OPTS="-Xmx64m" "-Xms64m"

@rem Find java.exe
if defined JAVA_HOME goto findJavaFromJavaHome

set JAVA_EXE=java.exe
%JAVA_EXE% -version >NUL 2>&1
if %ERRORLEVEL% equ 0 goto execute

echo. 1>&2
echo ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH. 1>&2
echo. 1>&2
echo Please set the JAVA_HOME variable in your environment to match the 1>&2
echo location of your Java installation. 1>&2

goto fail

:findJavaFromJavaHome
set JAVA_HOME=%JAVA_HOME:"=%
set JAVA_EXE=%JAVA_HOME%/bin/java.exe

if exist "%JAVA_EXE%" goto execute

echo. 1>&2
echo ERROR: JAVA_HOME is set to an invalid directory: %JAVA_HOME% 1>&2
echo. 1>&2
echo Please set the JAVA_HOME variable in your environment to match the 1>&2
echo location of your Java installation. 1>&2

goto fail

:execute
@rem Setup the command line

set CLASSPATH=%APP_HOME%\\gradle\\wrapper\\gradle-wrapper.jar

@rem Execute Gradle
"%JAVA_EXE%" %DEFAULT_JVM_OPTS% %JAVA_OPTS% %GRADLE_OPTS% "-Dorg.gradle.appname=%APP_BASE_NAME%" -classpath "%CLASSPATH%" org.gradle.wrapper.GradleWrapperMain %*

:end
@rem End local scope for the variables with windows NT shell
if %ERRORLEVEL% equ 0 goto mainEnd

:fail
rem Set variable GRADLE_EXIT_CONSOLE if you need the _script_ return code instead of
rem the _cmd.exe /c_ return code!
set EXIT_CODE=%ERRORLEVEL%
if %EXIT_CODE% equ 0 set EXIT_CODE=1
if not ""=="%GRADLE_EXIT_CONSOLE%" exit %EXIT_CODE%
exit /b %EXIT_CODE%

:mainEnd
if "%OS%"=="Windows_NT" endlocal

:omega
`
}

function genGradleWrapperProps(): string {
  return `# NexCube 自动生成 —— Gradle 8.1.1 (Forge 1.20.1 推荐)
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\\://services.gradle.org/distributions/gradle-8.1.1-bin.zip
networkTimeout=10000
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
`
}

/* ------------------------------------------------------------------ */
/* mods.toml / pack.mcmeta                                             */
/* ------------------------------------------------------------------ */

function genModsToml(project: CodegenProject): string {
  return `# mods.toml —— 由 NexCube 自动生成
# 占位符（\${var}）由 build.gradle 的 processResources 替换

modLoader="javafml"
loaderVersion="\${loader_version_range}"
license="\${mod_license}"
issueTrackerURL="https://example.com/issues"

[[mods]]
modId="\${mod_id}"
version="\${mod_version}"
displayName="\${mod_name}"
authors="\${mod_authors}"
description='''
\${mod_description}
'''

[[dependencies.\${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="\${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.\${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="\${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
`
}

function genPackMcmeta(): string {
  // pack_format 15 = MC 1.20 - 1.20.1
  return `{
  "pack": {
    "description": "\${mod_id} resources",
    "pack_format": 15
  }
}
`
}

/* ------------------------------------------------------------------ */
/* README.md / .gitignore                                              */
/* ------------------------------------------------------------------ */

function genReadme(project: CodegenProject): string {
  return `# ${project.name}

> 由 [NexCube](https://github.com/nexcube) IDE 自动生成的 Minecraft 模组骨架。

## 环境要求

- **Minecraft**: ${project.mcVersion}
- **Forge**: ${project.forgeVersion}
- **Java**: 17 (Forge 1.20.1 最低要求)
- **Gradle**: 8.1.1 (经 wrapper 自动下载)

## 构建 JAR

\`\`\`bash
# Unix
./gradlew build

# Windows
gradlew.bat build
\`\`\`

构建产物位于 \`build/libs/${project.modId}-${project.version}.jar\`，
可直接放入 \`mods/\` 文件夹使用。

## 启动测试客户端

\`\`\`bash
./gradlew runClient
\`\`\`

## 项目结构

\`\`\`
${project.modId}/
├── build.gradle
├── gradle.properties
├── settings.gradle
├── gradlew / gradlew.bat
├── src/main/java/com/${project.author.toLowerCase()}/${project.modId}/
│   ├── ${project.modId.split('_').map(s => s.charAt(0).toUpperCase() + s.slice(1)).join('')}Mod.java     # 主类
│   ├── block/   # 方块注册 + 自定义方块子类
│   ├── item/    # 物品注册 + 自定义物品子类
│   ├── entity/  # 实体注册 + 自定义实体子类
│   └── client/  # 客户端设置（渲染器、模型）
└── src/main/resources/
    ├── META-INF/mods.toml
    └── pack.mcmeta
\`\`\`

## 元信息

| 字段 | 值 |
|------|-----|
| modId | \`${project.modId}\` |
| 版本 | \`${project.version}\` |
| 作者 | \`${project.author}\` |
| 加载器 | Forge |
| MC 版本 | ${project.mcVersion} |
| Forge 版本 | ${project.forgeVersion} |

---

_Generated by NexCube IDE._
`
}

function genGitignore(): string {
  return `# Gradle
.gradle/
build/
out/

# IDE
.idea/
*.iml
*.ipr
*.iws
.vscode/
.settings/
.classpath
.project
bin/

# Forge
run/
run-data/

# OS
.DS_Store
Thumbs.db

# NexCube
.nexcube/
*.zip
`
}

/* ------------------------------------------------------------------ */
/* 公共入口：generateProjectFiles                                     */
/* ------------------------------------------------------------------ */

export interface ProjectFileBundle {
  files: GeneratedFile[]
}

/** 生成 build.gradle / gradle.properties / mods.toml 等项目文件 */
export function generateProjectFiles(
  project: CodegenProject,
  options: { includeReadme?: boolean; includeGitignore?: boolean } = {},
): ProjectFileBundle {
  const files: GeneratedFile[] = []

  files.push({ path: 'build.gradle', content: genBuildGradle() })
  files.push({ path: 'gradle.properties', content: genGradleProperties(project) })
  files.push({ path: 'settings.gradle', content: genSettingsGradle(project) })
  files.push({
    path: 'src/main/resources/META-INF/mods.toml',
    content: genModsToml(project),
  })
  files.push({
    path: 'src/main/resources/pack.mcmeta',
    content: genPackMcmeta(),
  })

  if (options.includeReadme !== false) {
    files.push({ path: 'README.md', content: genReadme(project) })
  }
  if (options.includeGitignore !== false) {
    files.push({ path: '.gitignore', content: genGitignore() })
  }

  return { files }
}

/** 生成 gradle wrapper 脚本（可选，UI 默认包含） */
export function generateGradleWrapper(): GeneratedFile[] {
  return [
    { path: 'gradlew', content: genGradlewUnix(), executable: true },
    { path: 'gradlew.bat', content: genGradlewWindows() },
    {
      path: 'gradle/wrapper/gradle-wrapper.properties',
      content: genGradleWrapperProps(),
    },
  ]
}
